### ISSUE TITLE
NEXTAUTH_URL port number not in effect

### ISSUE THREAD

**Issue by wuyuansheng1982** [linkwarden/linkwarden#144]
**Describe the bug**
I defined the url in the .env file.
NEXTAUTH_URL=http://localhost:3535

When I tried to start by running yarn start, it yields the following errors. How to rectify the issue?
- error Failed to start server
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1463:16)
    at listenInCluster (node:net:1511:12)
    at Server.listen (node:net:1599:7)
    at /root/linkwarden/node_modules/next/dist/server/lib/start-server.js:153:16
    at new Promise (<anonymous>)
    at startServer (/root/linkwarden/node_modules/next/dist/server/lib/start-server.js:134:11)
    at nextStart (/root/linkwarden/node_modules/next/dist/cli/next-start.js:77:40) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

**Comment by daniel31x13** [comment]
Hello @wuyuansheng1982,
For this to work on a different port other than 3000 (lets say 3535), change the last line in your [Dockerfile](https://github.com/linkwarden/linkwarden/blob/main/Dockerfile) to the following:

```dockerfile
CMD yarn prisma migrate deploy && yarn start -p 3535
```

**Comment by wuyuansheng1982** [comment]
@daniel31x13 Perfect, works now.
