### ISSUE TITLE
How can the network port be changed?

### ISSUE THREAD

**Issue by maitrenageur** [linkwarden/linkwarden#276]
**Is your question related to a problem or code? Please describe.**
I use the manual installation without Docker.
Everthing is fine, but I must change the port number. The standard value is 3000, but the environment variable change with:

`NEXTAUTH_URL=http://localhost:4000`

is not valid. The service use the port 3000 to every time. A rebuild with yarn ignore the new setting too. 

How can I change the network port?

**Comment by daniel31x13** [comment]
`yarn start -p 4000` should work

**Comment by maitrenageur** [comment]
> `yarn start -p 4000` should work

Thank you, it is the solution. And should be a part of the documentation.

**Comment by Morethanevil** [comment]
Hi, I tried bare metal installation, but I can not change the port. 


`yarn start -p 3334` does not work. 



```
 yarn start -p 3334
yarn run v1.22.21
$ concurrently "next start" "yarn worker:prod" -p 3334
3334 - error Failed to start server
3334 Error: listen EADDRINUSE: address already in use :::3000
3334     at Server.setupListenHandle [as _listen2] (node:net:1872:16)
3334     at listenInCluster (node:net:1920:12)
3334     at Server.listen (node:net:2008:7)
3334     at /apps/linkwarden/node_modules/next/dist/server/lib/start-server.js:153:16
3334     at new Promise (<anonymous>)
3334     at startServer (/apps/linkwarden/node_modules/next/dist/server/lib/start-server.js:134:11)
3334     at nextStart (/apps/linkwarden/node_modules/next/dist/cli/next-start.js:77:40) {
3334   code: 'EADDRINUSE',
3334   errno: -98,
3334   syscall: 'listen',
3334   address: '::',
3334   port: 3000
3334 }
3334 next start exited with code 1
```


Maybe this is related, the .env is not loaded when building

```
 yarn build
yarn run v1.22.21
$ next build
- error Failed to load env from /apps/linkwarden/.env TypeError: Cannot read properties of undefined (reading 'split')
    at /apps/linkwarden/node_modules/@next/env/dist/index.js:1:311
    at Array.reduce (<anonymous>)
    at _interpolate (/apps/linkwarden/node_modules/@next/env/dist/index.js:1:125)
    at expand (/apps/linkwarden/node_modules/@next/env/dist/index.js:1:709)
    at processEnv (/apps/linkwarden/node_modules/@next/env/dist/index.js:1:4018)
    at loadEnvConfig (/apps/linkwarden/node_modules/@next/env/dist/index.js:1:5009)
    at /apps/linkwarden/node_modules/next/dist/build/index.js:149:116
    at Span.traceFn (/apps/linkwarden/node_modules/next/dist/trace/trace.js:96:20)
    at /apps/linkwarden/node_modules/next/dist/build/index.js:149:81
    at Span.traceAsyncFn (/apps/linkwarden/node_modules/next/dist/trace/trace.js:103:26)
- info Linting and checking validity of types  
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
```


The same env is working fine in docker, but I wanted to use linkwarden directly on my host. I added the database URL.
