### ISSUE TITLE
HTTP Protocol not supported?

### ISSUE THREAD

**Issue by tinyn** [linkwarden/linkwarden#408]
**Describe the bug**
While attempting to add a new site, an error message was displayed which read 

"Something went wrong retrieving the file size"

Was not sure what was up. Checked the logs and found this

```
[0] TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
[0]     at new NodeError (node:internal/errors:405:5)
[0]     at new ClientRequest (node:_http_client:188:11)
[0]     at request (node:http:100:10)
[0]     at /data/node_modules/next/dist/compiled/node-fetch/index.js:1:65434
[0]     at new Promise (<anonymous>)
[0]     at fetch (/data/node_modules/next/dist/compiled/node-fetch/index.js:1:64996)
[0]     at getTitle (/data/.next/server/pages/api/v1/links.js:258:61)
[0]     at postLink (/data/.next/server/pages/api/v1/links.js:340:107)
[0]     at async links (/data/.next/server/pages/api/v1/links.js:454:25) {
[0]   code: 'ERR_INVALID_PROTOCOL'
[0] }
```

**To Reproduce**
Attempt to add this site

http://www.jazbo.com/videopoker/curves.html

**Comment by s4msy** [comment]
Looks like its the same as [#401 ](https://github.com/linkwarden/linkwarden/issues/401)

**Comment by tinyn** [comment]
Ahh, my mistake. I did not search hard enough to find that issue. I would concur, its the same. Lets close this issue and track the other.

**Comment by daniel31x13** [comment]
#401 is already resolved.
