### ISSUE TITLE
Unable to archive links using the http protocol as screenshots or pdf files

### ISSUE THREAD

**Issue by hchengting** [linkwarden/linkwarden#485]
**Describe the bug**
After adding a link using the http protocol and entering the archiving process, the docker container log shows the following error.
```
[1] Processing link http://eyny.com/forum.php?view=all for user 1
[1] TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
[1]     at new NodeError (node:internal/errors:405:5)
[1]     at new ClientRequest (node:_http_client:188:11)
[1]     at request (node:http:100:10)
[1]     at /data/node_modules/node-fetch/lib/index.js:1482:15
[1]     at new Promise (<anonymous>)
[1]     at fetch (/data/node_modules/node-fetch/lib/index.js:1451:9)
[1]     at validateUrlSize (/data/lib/api/validateUrlSize.ts:11:33)
[1]     at /data/lib/api/archiveHandler.ts:43:34
[1]     at archiveHandler (/data/lib/api/archiveHandler.ts:272:9)
[1]     at runNextTicks (node:internal/process/task_queues:60:5) {
[1]   code: 'ERR_INVALID_PROTOCOL'
[1] }
```
Therefore, the link cannot be archived as a screenshot or pdf file.

**To Reproduce**
1. Click on `New Link'
2. Add a link that starts with `http://`
3. Check for errors during archiving

**Expected behavior**
Links should be properly archived as screenshot and pdf.

**Linkwarden Version**
v2.4.9

**Additional context**
Errors similar to #408

**Comment by daniel31x13** [comment]
Hey there, a lot has changed. Has this been resolved? Will reopen this issue if it hasn't.
