### ISSUE TITLE
How to add EMAIL_SERVER string in manual installation

### ISSUE THREAD

**Issue by panchtatvam** [linkwarden/linkwarden#533]
I want to use my SMTP server but can't figure out how to setup the `EMAIL_SERVER` param with user name and password.

The documentation also doesn't provide a sample string for the `EMAIL_SERVER` setting.

Please provide details on how to add SMTP EMAIL_SERVER

**Comment by GoodM4ven** [comment]
Aren't these what you looking for?

https://docs.linkwarden.app/self-hosting/environment-variables#smtp-settings

**Comment by panchtatvam** [comment]
The documentation is incomplete with no mention of full SMTP string required Linkwarde.

**Comment by Mat-DB** [comment]
I am searching as well on how to set up linkwarden and SMTP.
Is it possible to just add one or more examples in the documentation?
Makes it easier to deploy instead of everyone having to go to "chatgpt or something" (which spits out a lot of trash sometimes but that is another topic)

**Comment by Morethanevil** [comment]
It is a little difficult, but not impossible. Add this in your .env

It should look like this

```
# SMTP Settings
NEXT_PUBLIC_EMAIL_PROVIDER=true
EMAIL_FROM=admin@domain.com
EMAIL_SERVER=smtps://admin%40domain.com:verylongpassword@smtp.domain.com:465
```

`smtps://username:yourpassword@your.smtp.server:port`

smtps is for SMTP with SSL / Starttls
admin@domain.com is the username for the SMTP server
password is selfexplaining
@smtp.domain.com is your SMTP-Server
465 is the port

But be aware, you need to [Percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters) for all special characters like @, % or & etc...

Example:

Passwordexample: **c%%L!73**

```
NEXT_PUBLIC_EMAIL_PROVIDER=true
EMAIL_FROM=admin@domain.com
EMAIL_SERVER=smtps://admin%40domain.com:c%25%25L%2173@smtp.domain.com:465
```


Do yourself a big favor and avoid $ or # in your passwords, they cause a lot of problems even with percent encoding!
A long password with upper and lower cases and ! or ? is secure enough.

**Comment by Mat-DB** [comment]
Thanks for the useful information!
I'll try this. I am going to use a google account. If I get it to work I'll comment my settings maybe it is useful for other people.

**Comment by blade10101** [comment]
[next-auth][error][SIGNIN_EMAIL_ERROR] 
[0] https://next-auth.js.org/errors#signin_email_error Cannot read properties of undefined (reading 'split') {
[0]   error: {
[0]     message: "Cannot read properties of undefined (reading 'split')",
[0]     stack: "TypeError: Cannot read properties of undefined (reading 'split')\n" +
[0]       '    at normalizer (/data/node_modules/next-auth/core/routes/signin.js:61:23)\n' +
[0]       '    at Object.signin (/data/node_modules/next-auth/core/routes/signin.js:66:15)\n' +
[0]       '    at AuthHandler (/data/node_modules/next-auth/core/index.js:260:39)\n' +
[0]       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
[0]       '    at async NextAuthApiHandler (/data/node_modules/next-auth/next/index.js:22:19)\n' +
[0]       '    at async auth (/data/.next/server/pages/api/v1/auth/[...nextauth].js:1666:12)',
[0]     name: 'TypeError'
[0]   },
[0]   providerId: 'email',
[0]   message: "Cannot read properties of undefined (reading 'split')"

**Comment by blade10101** [comment]
> It is a little difficult, but not impossible. Add this in your .env
> 
> It should look like this
> 
> ```
> # SMTP Settings
> NEXT_PUBLIC_EMAIL_PROVIDER=true
> EMAIL_FROM=admin@domain.com
> EMAIL_SERVER=smtps://admin%40domain.com:verylongpassword@smtp.domain.com:465
> ```
> 
> `smtps://username:yourpassword@your.smtp.server:port`
> 
> smtps is for SMTP with SSL / Starttls [admin@domain.com](mailto:admin@domain.com) is the username for the SMTP server password is selfexplaining @smtp.domain.com is your SMTP-Server 465 is the port
> 
> But be aware, you need to [Percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters) for all special characters like @, % or & etc...
> 
> Example:
> 
> Passwordexample: **c%%L!73**
> 
> ```
> NEXT_PUBLIC_EMAIL_PROVIDER=true
> EMAIL_FROM=admin@domain.com
> EMAIL_SERVER=smtps://admin%40domain.com:c%25%25L%2173@smtp.domain.com:465
> ```
> 
> Do yourself a big favor and avoid $ or # in your passwords, they cause a lot of problems even with percent encoding! A long password with upper and lower cases and ! or ? is secure enough.

your percent encoding is wrong

**Comment by Morethanevil** [comment]
This was just an example to lead in the right direction. My SMTP is running fine with my password

If you have a better example, share it with us!

**Comment by blade10101** [comment]
> This was just an example to lead in the right direction. My SMTP is running fine with my password
> 
> If you have a better example, share it with us!

nope, its broke like the S3 support. but other than the database crashing and having to erase everything, it works if you dfon't use the features.

**Comment by Morethanevil** [comment]
S3 is running fine 🤷🏻‍♂️

Made a screenshot from my MinIO
![Screenshot_2024-11-22-02-16-40-46_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/21e618ef-784b-4cdc-bedf-2dff995a4c39)


The password does not contain any special characters, as mentioned above

For all intrested people, here is my S3 example from the ENV:

```bash
# AWS S3 Settings
SPACES_KEY=user-name
SPACES_SECRET=password
SPACES_ENDPOINT=https://domain.com
SPACES_BUCKET_NAME=bucket
SPACES_REGION=self explaining
SPACES_FORCE_PATH_STYLE=true
```

**Comment by blade10101** [comment]
That's weird as I have it setup as I have other instances, but it dont give a error, just does nothing and the bucket never gets one file.

**Comment by roelven** [comment]
For anyone that arrived here like me searching for details on how to correctly configure your email server, here are some useful guidelines:

1. It's important to define the correct protocol depending on the port you want to use: 
  - `smtp://` with port 587 (STARTTLS)
  - `smtps://` with port 465 (Implicit SSL/TLS)
2. The values in the full string need to be URL-encoded, so characters like @, #, $, %, &, etc. need to be encoded.
3. After changing your .env file, a `$ docker compose restart` won't suffice, you'll need to do a `$ docker compose down` and `$ docker compose up -d` to have the new .env variables propagate. 

Good luck!

**Comment by g-vdn** [comment]
What worked for me: 

Set-up docker from start with smtp URI

SMTP URI:
smtps://linkwarden@domain.net:K5wJWkmNAZLQ@smtppro.mail.com:465

Docker host is running unRAID OS.

**Comment by optiprime** [comment]
> It just errors out if it tries to connect to the smtp server. I assume its broke as I have the settings correct.
> 
> [next-auth][error][SIGNIN_EMAIL_ERROR] [0] https://next-auth.js.org/errors#signin_email_error Cannot read properties of undefined (reading 'split') { [0] error: { [0] message: "Cannot read properties of undefined (reading 'split')", [0] stack: "TypeError: Cannot read properties of undefined (reading 'split')\n" + [0] ' at normalizer (/data/node_modules/next-auth/core/routes/signin.js:61:23)\n' + [0] ' at Object.signin (/data/node_modules/next-auth/core/routes/signin.js:66:15)\n' + [0] ' at AuthHandler (/data/node_modules/next-auth/core/index.js:260:39)\n' + [0] ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' + [0] ' at async NextAuthApiHandler (/data/node_modules/next-auth/next/index.js:22:19)\n' + [0] ' at async auth (/data/.next/server/pages/api/v1/auth/[...nextauth].js:1666:12)', [0] name: 'TypeError' [0] }, [0] providerId: 'email', [0] message: "Cannot read properties of undefined (reading 'split')"

Problem here is not the parsing of the EMAIL_SERVER config. The error appears if you try to login with username instead of email-address. Unfortunately this is required in the LinkDroid app.
