### ISSUE TITLE
Cannot create prevesered formats without root

### ISSUE THREAD

**Issue by monstermuffin** [linkwarden/linkwarden#550]
**Describe the bug**
When running the Linkwarden container as a non-root user, preserved formats never get created because `npx playwright install` doesn't work as per the logs below.

I do not run my containers as root, my deployment with ansible creates a user per container, sets this user as owner of the container's data directory and runs the container as said user.

**To Reproduce**
Define a user to run the container as using compose using `user`. 

I do this via ansible. `user: "{{ linkwarden_uid }}:{{ linkwarden_gid }}"`

**Expected behavior**
playwright should be installed without requiring root perms.

**Log**
```
[1] Processing link <somelink> for user 1
[1] Error processing link <somelink> for user 1: browserType.launch: Executable doesn't exist at /.cache/ms-playwright/chromium-1067/chrome-linux/chrome
[1] ╔═════════════════════════════════════════════════════════════════════════╗
[1] ║ Looks like Playwright Test or Playwright was just installed or updated. ║
[1] ║ Please run the following command to download new browsers:              ║
[1] ║                                                                         ║
[1] ║     npx playwright install                                              ║
[1] ║                                                                         ║
[1] ║ <3 Playwright Team                                                      ║
[1] ╚═════════════════════════════════════════════════════════════════════════╝
[1]     at archiveHandler (/data/lib/api/archiveHandler.ts:34:34)
[1]     at archiveLink (/data/scripts/worker.ts:98:27)
[1]     at /data/scripts/worker.ts:119:17
[1]     at processBatch (/data/scripts/worker.ts:119:6)
[1]     at async init (/data/scripts/worker.ts:134:7) {
[1]   name: 'Error'
[1] }
```

**Additional context**
If I try to run `npx playwright install` manually it will fail.

```
npx playwright install
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 999:994 "/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
I have no name!@ece36c86f950:/data$ Failed to install browsers
Error: EACCES: permission denied, mkdir '/.cache'
```

If I mount `.npm` and `.cache` to the host we can see the mounts are owned by root.

```
linkwarden linkwarden 4096 Apr  2 14:07 .
root       root       4096 Apr  2 13:57 ..
linkwarden linkwarden 4096 Apr  2 13:07 archives
root       root       4096 Apr  2 14:07 cache
inkwarden linkwarden  146 Apr  2 12:38 .env
 root       root       4096 Apr  2 14:07 npm
inkwarden linkwarden  807 Apr 23  2023 .profile
```
**Workaround**

An imperfect workaround to this is to mount the `.cache` and `.npm` directories on the host, and then manually `chown` the directory, which then allows me to run  `npx playwright install`

```
I have no name!@7c1df496066a:/data$ npx playwright install
Downloading Chromium 115.0.5790.24 (playwright build v1067) from https://playwright.azureedge.net/builds/chromium/1067/chromium-linux.zip
146.4 Mb [====================] 100% 0.0s
Chromium 115.0.5790.24 (playwright build v1067) downloaded to /.cache/ms-playwright/chromium-1067
Downloading FFMPEG playwright build v1009 from https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip
2.6 Mb [====================] 100% 0.0s
FFMPEG playwright build v1009 downloaded to /.cache/ms-playwright/ffmpeg-1009
Downloading Firefox 113.0 (playwright build v1408) from https://playwright.azureedge.net/builds/firefox/1408/firefox-debian-11.zip
78.8 Mb [====================] 100% 0.0s
Firefox 113.0 (playwright build v1408) downloaded to /.cache/ms-playwright/firefox-1408
Downloading Webkit 16.4 (playwright build v1860) from https://playwright.azureedge.net/builds/webkit/1860/webkit-debian-11.zip
80.4 Mb [====================] 100% 0.0s
Webkit 16.4 (playwright build v1860) downloaded to /.cache/ms-playwright/webkit-1860
npm notice
npm notice New major version of npm available! 9.8.1 -> 10.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.0
npm notice Run npm install -g npm@10.5.0 to update!
npm notice
```
Previews now work. 

This is obviously not ideal as it will not persist with container recreations, and keeping these directories mounted to the host is unnecessary.

**Comment by daniel31x13** [comment]
Hey there, a lot has changed. Has this been resolved? Will reopen this issue if it hasn't.
