### ISSUE TITLE
After updating to 2.6.0, Preserved Formats seems to be unable to generate.

### ISSUE THREAD

**Issue by dragonjay-lyj** [linkwarden/linkwarden#655]
**Describe the bug**
In the previous version (was it 2.6.0?), at least one Readable format could be generated, but in this latest version, nothing is produced.

**To Reproduce**
Normal steps for adding a link

**Expected behavior**
At least one Readable format can be generated.

**Screenshots**
![mmexport1721423389602.png](https://github.com/user-attachments/assets/7aeb3dfe-029e-407d-a160-24ce9183790e)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome]
 - Version []

**Smartphone (please complete the following information):**
 - Device: [Redmi K60 pro]
 - OS: [Android 14]
 - Browser [chrome]
 - Version []

**Additional context**
I took a look at the log (as shown in the image) and it seems that the generation failure is due to a timeout error. Is it possible to extend the time limit?

**Comment by daniel31x13** [comment]
How about other links? Same issue? (Like [this](https://news.ycombinator.com) one)
Also did you take the manual installation or installation using docker compose?

**Comment by dragonjay-lyj** [comment]
> How about other links? Same issue? (Like [this](https://news.ycombinator.com) one) Also did you take the manual installation or installation using docker compose?

Ah, when I first installed it, you hadn't updated the version yet, which was 2.6.0. At that time, I installed it using Docker and was able to generate one Readable format. Later, I wanted to try a manual installation, so I deleted Docker, but it was around this time that you updated the version. To test my theory, I tried both Docker and manual installation in the new version, and neither method was able to generate a Readable format.

**Comment by dragonjay-lyj** [comment]
> How about other links? Same issue? (Like [this](https://news.ycombinator.com) one) Also did you take the manual installation or installation using docker compose?

Regarding the link, as I mentioned, in the previous version, it was possible to generate a Readable format.

**Comment by dragonjay-lyj** [comment]
Also, forgive me for getting the version number wrong. The latest version should be 2.6.0.

**Comment by dragonjay-lyj** [comment]
I’ve confirmed it. I just tested and it is indeed an issue with the new version. I rolled back to 2.5.2 and successfully generated a Readable format.

<img width="744" alt="c49c7e0e70066679911ec4e32eac6b5" src="https://github.com/user-attachments/assets/94b4dded-a665-441a-9d70-e5acd970df63">

I encountered some issues during the rollback process.

I used Manual Installation, and when executing the command `npx playwright install-deps`, I encountered this error: `E: Malformed entry 1 in list file /etc/apt/sources.list.d/docker.list (URI parse)`. `E: The list of sources could not be read.` `Failed to install browser dependencies`. `Error: Installation process exited with code: 100`. However, this didn't have a significant impact (it might also be an issue with my host configuration). After running `yarn start`, I encountered the following problem:
```
Error processing links:[0m PrismaClientInitializationError: 
 Invalid `prisma.link.findMany()` invocation in
 /root/linkwarden/scripts/worker.ts:17:43
 
   14 };
   15 
   16 async function processBatch() {
 → 17   const linksOldToNew = await prisma.link.findMany(
 Prisma Client could not locate the Query Engine for runtime "debian-openssl-1.0.x".
 
 This happened because Prisma Client was generated for "debian-openssl-3.0.x", but the actual deployment required "debian-openssl-1.0.x".
 Add "debian-openssl-1.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
 
 generator client {
   provider      = "prisma-client-js"
   binaryTargets = ["native", "debian-openssl-1.0.x"]
 }
 
 The following locations have been searched:
   /root/linkwarden/node_modules/.prisma/client
   /root/linkwarden/node_modules/@prisma/client
   /tmp/prisma-engines
   /root/linkwarden/prisma
     at Rn.handleRequestError (/root/linkwarden/node_modules/@prisma/client/runtime/library.js:174:7601)
     at Rn.handleAndLogRequestError (/root/linkwarden/node_modules/@prisma/client/runtime/library.js:174:6754)
     at /root/linkwarden/node_modules/@prisma/client/runtime/library.js:177:3010
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async /root/linkwarden/node_modules/@prisma/client/runtime/library.js:177:3225
     at async t._executeRequest (/root/linkwarden/node_modules/@prisma/client/runtime/library.js:177:11403)
     at async processBatch (/root/linkwarden/scripts/worker.ts:17:25)
     at async init (/root/linkwarden/scripts/worker.ts:134:7) {
   clientVersion: '4.16.2',
   errorCode: undefined
 }
```
Following the instructions, I searched for `generator client` in the `schema.prisma` file and added `binaryTargets = ["native", "debian-openssl-1.0.x"]`. Then, running `npx prisma generate` successfully resolved the issue.

**Comment by TheLinuxGuy** [comment]
I just did a fresh new install of 2.6.0 and I am also seeing this generation issue. 
![Screenshot 2024-07-20 at 1 44 54 AM](https://github.com/user-attachments/assets/fc33b904-5d13-4549-b3e4-c8d32f81c538)

**Comment by daniel31x13** [comment]
@TheLinuxGuy using docker or manual installation?

For those of you who are using the manual installation you need to run `yarn playwright install` right after `npx playwright install-deps`. This is something I need to add in the docs...

**Comment by dragonjay-lyj** [comment]
[1] $ ts-node --transpile-only --skip-project scripts/worker.ts
[0] - [36minfo[39m Loaded env from /root/linkwarden/.env
[1] [34mStarting the link processing task[0m
[1] [34mProcessing link https://www.gameinformer.com/2022/09/10/assassins-creed-mirage-reveal-trailer-released-game-launching-in-2023 for user 1[0m
[1] prisma:query BEGIN
[1] prisma:query SELECT &quot;public&quot;.&quot;Link&quot;.&quot;id&quot; FROM &quot;public&quot;.&quot;Link&quot; WHERE (&quot;public&quot;.&quot;Link&quot;.&quot;id&quot; = $1 AND 1=1)
[1] prisma:query COMMIT
[1] Found og:image URL: https://www.gameinformer.com/sites/default/files/styles/thumbnail/public/2022/09/10/a8b85a7b/mirage4.jpg
[1] prisma:query BEGIN
[1] prisma:query COMMIT
[1] page.goBack: Timeout 30000ms exceeded.
[1] Call log:
[1]   - waiting for navigation until &quot;load&quot;
[1]   -   navigated to &quot;https://www.gameinformer.com/2022/09/10/assassins-creed-mirage-reveal-trailer-released-game-launching-in-2023&quot;
[1] 
[1]     at handleArchivePreview (/root/linkwarden/lib/api/preservationScheme/handleArchivePreview.ts:34:16)
[1]     at /root/linkwarden/async /root/linkwarden/lib/api/archiveHandler.ts:128:13
[1]     at async archiveHandler (/root/linkwarden/lib/api/archiveHandler.ts:64:5)
[1]     at async archiveLink (/root/linkwarden/scripts/worker.ts:112:7)
[1]     at async processBatch (/root/linkwarden/scripts/worker.ts:135:3)
[1]     at async init (/root/linkwarden/scripts/worker.ts:148:7) {
[1]   name: &#x27;TimeoutError&#x27;
[1] }
[1] prisma:query SELECT 1
[1] prisma:query BEGIN
[1] prisma:query COMMIT
[1] [34mError processing link https://www.gameinformer.com/2022/09/10/assassins-creed-mirage-reveal-trailer-released-game-launching-in-2023 for user 1:[0m page.goBack: Timeout 30000ms exceeded.
[1] Call log:
[1]   - waiting for navigation until &quot;load&quot;
[1]   -   navigated to &quot;https://www.gameinformer.com/2022/09/10/assassins-creed-mirage-reveal-trailer-released-game-launching-in-2023&quot;
[1] 
[1]     at handleArchivePreview (/root/linkwarden/lib/api/preservationScheme/handleArchivePreview.ts:34:16)
[1]     at /root/linkwarden/async /root/linkwarden/lib/api/archiveHandler.ts:128:13
[1]     at async archiveHandler (/root/linkwarden/lib/api/archiveHandler.ts:64:5)
[1]     at async archiveLink (/root/linkwarden/scripts/worker.ts:112:7)
[1]     at async processBatch (/root/linkwarden/scripts/worker.ts:135:3)
[1]     at async init (/root/linkwarden/scripts/worker.ts:148:7) {
[1]   name: &#x27;TimeoutError&#x27;
[1] }

**Comment by mdlaat** [comment]
Confirmed. Docker install. Upgraded from 2.5.3

**Comment by fmunim** [comment]
Having this issue as well, any solution?

Link:

https://www.thetimes.com/comment/columnists/article/dont-replace-the-culture-war-with-class-war-98xllvd80


Error:
![image](https://github.com/user-attachments/assets/35ebe230-e5bf-4146-af35-1fad588b94a2)

Installed manually, ran via screen

**Comment by Yehuda-Bergstein** [comment]
I'm also getting this error with this link - 
https://www.theclevercarrot.com/2020/05/homemade-fluffy-sourdough-pancakes/
on version [v2.13.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.13.0)

**Comment by daniel31x13** [comment]
Rootless setup is now supported: https://github.com/linkwarden/linkwarden/releases/tag/v2.16.1
