### ISSUE TITLE
Using linkwarden on intranet (without internet access)

### ISSUE THREAD

**Issue by fredbcode** [linkwarden/linkwarden#705]
I'm trying linkwarden (Docker) in a local intranet network and there is no preview picture
Seems related with

```
linkwarden_1      | [0] TypeError: fetch failed
linkwarden_1      | [0]     at Object.fetch (node:internal/deps/undici/undici:11372:11)
linkwarden_1      | [0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
linkwarden_1      | [0]     at async imageOptimizer (/data/node_modules/next/dist/server/image-optimizer.js:521:29)
linkwarden_1      | [0]     at async cacheEntry.imageResponseCache.get.incrementalCache (/data/node_modules/next/dist/server/next-server.js:414:72)
linkwarden_1      | [0]     at async /data/node_modules/next/dist/server/response-cache/index.js:99:36 {
linkwarden_1      | [0]   cause: Error: getaddrinfo ENOTFOUND t2.gstatic.com
linkwarden_1      | [0]       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
linkwarden_1      | [0]     errno: -3008,
linkwarden_1      | [0]     code: 'ENOTFOUND',
linkwarden_1      | [0]     syscall: 'getaddrinfo',
linkwarden_1      | [0]     hostname: 't2.gstatic.com'
linkwarden_1      | [0]   }
linkwarden_1      | [0] }
```

**Comment by daniel31x13** [comment]
It needs internet to generate the previews.

**Comment by fredbcode** [comment]
Maybe an option to turn it off ?

**Comment by LowHanger** [comment]
Same here - all of my local (intranet) links are missing preview images.  All of the external (internet) links seem to generate previews just fine.  Strange.

**Comment by daniel31x13** [comment]
Custom preview image is one of the features of the next release. 🔜
