### ISSUE TITLE
Change timeout for SSO?

### ISSUE THREAD

**Issue by zodac** [linkwarden/linkwarden#788]
**Is your question related to a problem or code? Please describe.**
Is it possible to increase the timeout for SSO requests? My Authentik instance is on another server an there is some times a delay between devices. I'd like to be able to set an environment variable or something to extend this.

**Describe what you've tried to solve this question**
Just retry when the connection is better.

**Include any code or screenshots (if applicable)**
I'm basing this off the error message in the logs when my authentication request to Authentik fails:

`message: 'outgoing request timed out after 3500ms'`

**Comment by AnonymousX86** [comment]
I'm facing the same issue. Full error:

```
[next-auth][error][SIGNIN_OAUTH_ERROR]
https://next-auth.js.org/errors#signin_oauth_error outgoing request timed out after 3500ms {
  error: {
    message: 'outgoing request timed out after 3500ms',
    stack: 'RPError: outgoing request timed out after 3500ms\n' +
      '    at /data/node_modules/openid-client/lib/helpers/request.js:137:13\n' +
      '    at async Issuer.discover (/data/node_modules/openid-client/lib/issuer.js:144:24)\n' +
      '    at async openidClient (/data/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
      '    at async getAuthorizationUrl (/data/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
      '    at async Object.signin (/data/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
      '    at async AuthHandler (/data/node_modules/next-auth/core/index.js:260:26)\n' +
      '    at async NextAuthApiHandler (/data/node_modules/next-auth/next/index.js:22:19)\n' +
      '    at async auth (/data/.next/server/pages/api/v1/auth/[...nextauth].js:1585:12)',
    name: 'RPError'
  },
  providerId: 'authentik',
  message: 'outgoing request timed out after 3500ms'
}
```

Which is weird because I have set up eight OIDC providers in Authentik (alongside other types, but that's not important, I guess), daily used by 2~4 people, and I've never came across timeout issue.

My config for context.

```env
# .env
# Required fields
NEXTAUTH_URL="https://linkwarden.example.com/api/v1/auth"
NEXTAUTH_SECRET="REDACTED"
POSTGRES_PASSWORD="REDACTED"
# General login
NEXT_PUBLIC_DISABLE_REGISTRATION="false"
NEXT_PUBLIC_CREDENTIALS_ENABLED="true"
DISABLE_NEW_SSO_USERS="false"
# Authentik
NEXT_PUBLIC_AUTHENTIK_ENABLED="true"
AUTHENTIK_CUSTOM_NAME="Authentik"
AUTHENTIK_ISSUER="https://authentik.example.com/application/o/linkwarden"
AUTHENTIK_CLIENT_ID="REDACTED"
AUTHENTIK_CLIENT_SECRET="REDACTED"
```

**Comment by jvanbruegge** [comment]
You can work around this by patching the sources like this: https://github.com/jvanbruegge/server-config/blob/9306f62dd1aeb04873da4671966f87abc47b0adb/caladan/linkwarden.nix#L14

**Comment by SwallowYourDreams** [comment]
I'm getting the exact same errors on Authentik. Being able to set the timeout via environment variables would be great to avoid this.

**Comment by thaddl** [comment]
Hej, I'm getting also this kind of error. Did someone found a fix for this?

**Comment by rahulparekh** [comment]
Running into the same issue as well

**Comment by SwallowYourDreams** [comment]
> You can work around this by patching the sources like this: https://github.com/jvanbruegge/server-config/blob/9306f62dd1aeb04873da4671966f87abc47b0adb/caladan/linkwarden.nix#L14
> 
> (And then set `LINKWARDEN_OAUTH_TIMEOUT` to something reasonable)

I am aware that you are trying to help by providing a quick fix, and I appreciate that, mate. Yet, the whole point of Docker deployments is to reduce complexity. Messing about with the sources is the opposite of that.

**Comment by jvanbruegge** [comment]
That's why I said "workaround" not "fix". Of course this is still an issue, but this way I can at least use linkwarden at all.
Fixing this in linkwarden itself is not hard, however instead of just adding N new env vars (one per auth provider), the oidc implementation should be refactored to be generic for any IdP. It *is* a standard after all.

**Comment by thinkhead** [comment]
I had to do some digging, I thought I could share it with other people who are having the same issue.
I'm using Kubernetes and as of linkwarden 2.11 the current workaround does not work. The file has been moved to:
`/data/pages/api/v1/auth/[...nextauth].ts`

With a simple lifecycle I can use the workaround, example for reference:
`lifecycle:
  postStart: "sed -i 's/AUTHENTIK_ISSUER,/AUTHENTIK_ISSUER,httpOptions: { timeout: Number(process.env.LINKWARDEN_OAUTH_TIMEOUT)},/g' /data/apps/web/pages/api/v1/auth/'[...nextauth].ts'"`

And now in 2.12... things got more complicated. Even if the file is modified, I still got a timeout error after 3500ms (the default value). I think (and assume based on my findings) that JavaScript is now compiled during the Docker build process, so before my postStart hook runs. Thus, modifying the TypeScript source doesn't affect the running application.

After a little bit of research, I found the node modules in the Docker container:
`/data/apps/web/.next/server/pages/api/v1/auth/[...nextauth].js.nft.json
/data/apps/web/.next/server/pages/api/v1/auth/[...nextauth].js
/data/apps/web/pages/api/v1/auth/[...nextauth].ts`

And voila! A new postStart version that fixed the problem:
`lifecycle:
  postStart: "sed -i 's/issuer: process__WEBPACK_IMPORTED_MODULE_65__.env.AUTHENTIK_ISSUER,/issuer: process__WEBPACK_IMPORTED_MODULE_65__.env.AUTHENTIK_ISSUER, httpOptions: { timeout: Number(process__WEBPACK_IMPORTED_MODULE_65__.env.LINKWARDEN_OAUTH_TIMEOUT) || 10000 },/g' /data/apps/web/.next/server/pages/api/v1/auth/'[...nextauth].js'"`

**Comment by krim404** [comment]
Any chance for this issue to be fixed? Authentik is very widespread and i've never seen an instance where it answered in less than 2s...

i "fixed" it in my setup (kubernetes) by hotpatching, but it feels really dirty to me:
```
          command:
            - /bin/sh
            - -c
            - |
              sed -i 's/timeout: 3500/timeout: 10000/g' /data/node_modules/openid-client/lib/helpers/request.js
              yarn prisma:deploy && yarn concurrently:start
