### ISSUE TITLE
Linkwarden error 500

### ISSUE THREAD

**Issue by niaishi** [linkwarden/linkwarden#819]
**Describe the bug**
Syncing with Linkwarden produces an error 500

```
TypeError: Cannot read properties of undefined (reading 'trim')
at postLink (/data/.next/server/pages/api/v1/links.js:586:49)
at async links (/data/.next/server/pages/api/v1/links.js:721:25)
```
**To Reproduce**
1. Activate normal sync

**Expected behavior**
Should sync normally with Linkwarden

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version: Latest

**Comment by daniel31x13** [comment]
This is probably going to be fixed in the next release, it's probably sending a required field which is null.

**Comment by marcelklehr** [comment]
Floccus still produces 500 errors occasionally

**Comment by marcelklehr** [comment]
(I see these regularly in CI against cloud.linkwarden.app, could you check your monitoring for 500 errors?)
