### ISSUE TITLE
Support for Webp format images for Preview Images

### ISSUE THREAD

**Issue by Danie10** [linkwarden/linkwarden#862]
**Is your feature request related to a problem? Please describe.**
No problem really.

**Describe the solution you'd like**
When uploading an image to the link Preview Image, maybe also being able to upload Webp format.

**Describe alternatives you've considered**
I did try to change the file filter on the file explorer from Customised to All files. It does upload the Webp file and Linkwarden reports it as updated, but it does not display at all.

**Additional context**
Webp is substantially smaller in size and really ideal for web services. It would therefore take up less storage and should load faster. I already use Webp format for all my blogging and on my WordPress site so I have everything already in Webp format.

BTW: Really loving the latest update!

**Comment by Danie10** [comment]
Ping to keep my request alive

**Comment by baali** [comment]
I ran into this issue. There are bunch of places where we don't include `webp` formats:
1. `apps/web/pages/api/v1/archives/[linkId].ts` has `allowedMIMETypes` 
2. `apps/worker/lib/archiveHandler.ts` has `imageExtension` variable and `determineLinkType` function
3. `packages/lib/generatePreview.ts` which uses `jimp` library to create a preview. This specially uses [`jimp`](https://www.npmjs.com/package/jimp) library to create a thumbnail. 

Currently `packages/lib/package.json` has jimp pinned to: `"jimp": "^0.22.10",`. I have been messing around with this library to make linkwarden work with webp images. 

There is a [gist](https://gist.github.com/ChaseIngebritson/61596510c80479247366bcc87e3e0ef5) on handling webp image and converting to other file format. This uses a DEPRECATED library:  [web-converter](https://github.com/scionoftech/webp-converter).

Jimp's latest release has a [fix](https://github.com/jimp-dev/jimp/issues/144#issuecomment-774672335) that has [documentation](https://jimp-dev.github.io/jimp/guides/webp/) on how it supports webp format. I have tried to use their example but I get an error:

```
root@85f72eaa0912:/home/node# npx tsx image.ts 
node:internal/modules/esm/resolve:313
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/node/node_modules/@jimp/wasm-webp/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:313:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:603:13)
    at resolveExports (node:internal/modules/cjs/loader:661:36)
    at Module._findPath (node:internal/modules/cjs/loader:753:31)
    at node:internal/modules/cjs/loader:1391:27
    at nextResolveSimple (/home/node/node_modules/tsx/dist/register-D2KMMyKp.cjs:3:942)
    at /home/node/node_modules/tsx/dist/register-D2KMMyKp.cjs:2:2550
    at /home/node/node_modules/tsx/dist/register-D2KMMyKp.cjs:2:1624
    at resolveTsPaths (/home/node/node_modules/tsx/dist/register-D2KMMyKp.cjs:3:760)
    at /home/node/node_modules/tsx/dist/register-D2KMMyKp.cjs:3:1038 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v24.0.2
``` 

I understand that [`export`](https://nodejs.org/api/packages.html#package-entry-points) is more modern version of making a module available in npm ecosystem, and I tried different node versions to see if I can make the library work, without success. At this point I don't have other potential lead, I would be happy to pick it up and create a PR if there is an alternative.

**Comment by Danie10** [comment]
OK thanks for looking at it. I suppose it is maybe about how other applications are handling webp for example I can upload a webp image fine into Mastodon.
