### ISSUE TITLE
preserved formats queue seems to be stuck

### ISSUE THREAD

**Issue by mdlaat** [linkwarden/linkwarden#926]
**Is your question related to a problem or code? Please describe.**
Since a few months, preserved formats  seem not being generated. When editing a link, it shows:
 `Link preservation is in the queue
Please check back later to see the result`

**Describe what you've tried to solve this question**
Recreated container & image. Container is running as root.

**Additional context**
docker logs linkwarden shows a lot of lines like this:
`[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://wisycom.com/usa/product/wisycom-manager/&size=32 404
`
docker logs postgres shows no errors.

Is there a way to check the queuestatus?

**Comment by flashground** [comment]
I have the same thing. Endless loading of pictures and the docker container logs are full:
`[0] upstream image response failed for https://... 404`
and also
```
[Error: ENOENT: no such file or directory, unlink '/data/data/archives/1/1.html'] {
[0]   errno: -2,
[0]   code: 'ENOENT',
[0]   syscall: 'unlink',
[0]   path: '/data/data/archives/1/1.html'
[0] }
```
I reinstalled everything several times.

**Comment by flashground** [comment]
> Strange, what version is the instance?

In my case: latest 2.8.4
of settings only NEXTAUTH_URL with my domain and NEXTAUTH_SECRET.

**Comment by mdlaat** [comment]
> Strange, what version is the instance?

image: ghcr.io/linkwarden/linkwarden:latest
webinterface reports 2.8.4

**Comment by daniel31x13** [comment]
The `upstream image response` errors aren't something to be worried about, it's just telling the server the requested favicon wasn't found...

Regarding the preservation, can you please do the following:
1. Restart the server.
2. Add a link, something like: https://example.com
3. Do nothing, for 30 seconds.
4. Copy the logs from the moment you restarted the server and send it here.

**Comment by mdlaat** [comment]
Here you go. Added a link to example.com right after restarting the docker container. Thank you.
`
yarn run v1.22.19
$ /data/node_modules/.bin/prisma migrate deploy
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"

52 migrations found in prisma/migrations


No pending migrations to apply.
Done in 1.35s.
yarn run v1.22.19
$ concurrently -P "next start {@}" "yarn worker:prod" --
[1] $ ts-node --transpile-only --skip-project scripts/worker.ts
[0] - ready started server on 0.0.0.0:3000, url: http://localhost:3000
[1] [34mProcessing the links...[0m
[1] [34mProcessing link https://{redacted} for user 1[0m
[1] [34mProcessing link https://{redacted} for user 1[0m
[1] [34mProcessing link https://{redacted} for user 1[0m
[1] [34mProcessing link https://{redacted} for user 1[0m
[1] [34mProcessing link https://{redacted} for user 1[0m
[1] [34mProcessing link https://{redacted} for user 1[0m
[1] [34mProcessing link https://{redacted} for user 1[0m
[1] [34mProcessing link https://{redacted} for user 1[0m
[1] [34mProcessing link https://{redacted} for user 1[0m
[1] [34mProcessing link https://{redacted} for user 1[0m
[1] [34mError processing link https://{redacted} for user 1:[0m browserContext.newPage: Target page, context or browser has been closed
[1]     at archiveHandler (/data/lib/api/archiveHandler.ts:70:30)
[1]     at async archiveLink (/data/scripts/worker.ts:112:7)
[1]     at async processBatch (/data/scripts/worker.ts:135:3)
[1]     at async init (/data/scripts/worker.ts:148:7)
[1] [34mError processing link https://{redacted} for user 1:[0m browserContext.newPage: Target page, context or browser has been closed
[1]     at archiveHandler (/data/lib/api/archiveHandler.ts:70:30)
[1]     at async archiveLink (/data/scripts/worker.ts:112:7)
[1]     at async processBatch (/data/scripts/worker.ts:135:3)
[1]     at async init (/data/scripts/worker.ts:148:7)
[1] [34mError processing link https://{redacted} for user 1:[0m browserContext.newPage: Target page, context or browser has been closed
[1]     at archiveHandler (/data/lib/api/archiveHandler.ts:70:30)
[1]     at async archiveLink (/data/scripts/worker.ts:112:7)
[1]     at async processBatch (/data/scripts/worker.ts:135:3)
[1]     at async init (/data/scripts/worker.ts:148:7)
[1] /data/lib/api/archiveHandler.ts:41
[1]           new Error(
[1]           ^
[1] Error: Browser has been open for more than 5 minutes.
[1]     at Timeout._onTimeout (/data/lib/api/archiveHandler.ts:41:11)
[1]     at listOnTimeout (node:internal/timers:569:17)
[1]     at processTimers (node:internal/timers:512:7)
[1] error Command failed with exit code 1.
[1] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] yarn worker:prod exited with code 1
[0] [33m[1mWarning: [22m[39mFor production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
[0] Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://example.com/&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://example.com/&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://example.com/&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://example.com/&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] [Error: ENOENT: no such file or directory, unlink '/data/data/archives/1/199.pdf'] {
[0]   errno: [33m-2[39m,
[0]   code: [32m'ENOENT'[39m,
[0]   syscall: [32m'unlink'[39m,
[0]   path: [32m'/data/data/archives/1/199.pdf'[39m
[0] }
[0] [Error: ENOENT: no such file or directory, unlink '/data/data/archives/1/199.png'] {
[0]   errno: [33m-2[39m,
[0]   code: [32m'ENOENT'[39m,
[0]   syscall: [32m'unlink'[39m,
[0]   path: [32m'/data/data/archives/1/199.png'[39m
[0] }
[0] [Error: ENOENT: no such file or directory, unlink '/data/data/archives/1/199.html'] {
[0]   errno: [33m-2[39m,
[0]   code: [32m'ENOENT'[39m,
[0]   syscall: [32m'unlink'[39m,
[0]   path: [32m'/data/data/archives/1/199.html'[39m
[0] }
[0] [Error: ENOENT: no such file or directory, unlink '/data/data/archives/1/199_readability.json'] {
[0]   errno: [33m-2[39m,
[0]   code: [32m'ENOENT'[39m,
[0]   syscall: [32m'unlink'[39m,
[0]   path: [32m'/data/data/archives/1/199_readability.json'[39m
[0] }
[0] [Error: ENOENT: no such file or directory, unlink '/data/data/archives/1/199.jpeg'] {
[0]   errno: [33m-2[39m,
[0]   code: [32m'ENOENT'[39m,
[0]   syscall: [32m'unlink'[39m,
[0]   path: [32m'/data/data/archives/1/199.jpeg'[39m
[0] }
[0] [Error: ENOENT: no such file or directory, unlink '/data/data/archives/1/199.jpg'] {
[0]   errno: [33m-2[39m,
[0]   code: [32m'ENOENT'[39m,
[0]   syscall: [32m'unlink'[39m,
[0]   path: [32m'/data/data/archives/1/199.jpg'[39m
[0] }
[0] [Error: ENOENT: no such file or directory, unlink '/data/data/archives/preview/1/199.jpeg'] {
[0]   errno: [33m-2[39m,
[0]   code: [32m'ENOENT'[39m,
[0]   syscall: [32m'unlink'[39m,
[0]   path: [32m'/data/data/archives/preview/1/199.jpeg'[39m
[0] }
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://example.com/&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
[0] upstream image response failed for https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://{redacted}&size=32 [33m404[39m
`

**Comment by rickykresslein** [comment]
I'm also getting a bunch of `upstream image response failed` and when I add a bookmark for my Homarr dashboard it crashes linkwarden and I have to log in again.

**Comment by mayzyo** [comment]
Same issue here
![image](https://github.com/user-attachments/assets/2fc854bf-3ad7-446f-9c6d-53b163f2d829)

**Comment by mdlaat** [comment]
I might have fixed it for me. There are still a lot of `upstream image response failed` errors, but at least the preserved formats are being generated again.

I had resource limits in my compose file. Both postgress & linkwarden were limited to 1 cpu and 1G mem. I now have postgress limited to 1 cpu/2G and linkwarden to 1cpu/4G and it seems working.

**Comment by daniel31x13** [comment]
> I might have fixed it for me. There are still a lot of upstream image response failed errors, but at least the preserved formats are being generated again.
>
> I had resource limits in my compose file. Both postgress & linkwarden were limited to 1 cpu and 1G mem. I now have postgress limited to 1 cpu/2G and linkwarden to 1cpu/4G and it seems working.

@mdlaat happy to hear! As I mentioned earlier, the `upstream image response failed` is another way of saying "There isn't an icon for a specific link..."

Links like https://example.com don't have a favicon:
<img width="505" alt="image" src="https://github.com/user-attachments/assets/89c93bc9-a012-4078-953d-f63d6529597e" />


On the other hand links like https://github.com _do_ have it:
<img width="505" alt="image" src="https://github.com/user-attachments/assets/a6feb9d6-b761-48e6-a920-4a0b54dab1c2" />


The way Linkwarden works is that it retrieves each link’s favicon in real time by using Google's content delivery service `(https://t2.gstatic.com)`. 
If no favicon is available, it displays a default link icon; hence, the server logs an `upstream image response failed` error message. Worth mentioning that the favicon retrieval is the only part that's not archived on the server, so the icon is fetched from the client side each time it’s requested:
![image](https://github.com/user-attachments/assets/a26c6e48-62d6-4a51-b380-6e735917c405)

Tried to explain it as clearly as possible—hope it helps!

**Comment by mayzyo** [comment]
> I might have fixed it for me. There are still a lot of `upstream image response failed` errors, but at least the preserved formats are being generated again.
> 
> I had resource limits in my compose file. Both postgress & linkwarden were limited to 1 cpu and 1G mem. I now have postgress limited to 1 cpu/2G and linkwarden to 1cpu/4G and it seems working.

Can confirm bumping it up to 4GB fixed my issue as well, but this does make Linkwarden a pretty heavy application imo. hoping it can be reduced in future releases.

**Comment by KagurazakaIris** [comment]
I'd like to know if there is a way to opt out of showing the favicon? I'm in an area with limited internet access, so I can't always connect to Google services.

**Comment by KagurazakaIris** [comment]
<img width="248" height="322" alt="Image" src="https://github.com/user-attachments/assets/006e510d-6dd6-4e70-86c5-79a18febbfde" />

By looking for related components, I found that it was actually stored in the browser localStorage, my problem was alleviated.
