### ISSUE TITLE
Uploading files fail to render

### ISSUE THREAD

**Issue by dannosaur** [linkwarden/linkwarden#941]
**Describe the bug**
Attempting to upload a PDF fails, with the following emitted in the error log;

```
Dec 28 16:32:13 linkwarden yarn[42598]: [0] TypeError: Only absolute URLs are supported
Dec 28 16:32:13 linkwarden yarn[42598]: [0]     at getNodeRequestOptions (/opt/linkwarden/node_modules/next/dist/compiled/node-fetch/index.js:1:63531)
Dec 28 16:32:13 linkwarden yarn[42598]: [0]     at /opt/linkwarden/node_modules/next/dist/compiled/node-fetch/index.js:1:65062
Dec 28 16:32:13 linkwarden yarn[42598]: [0]     at new Promise (<anonymous>)
Dec 28 16:32:13 linkwarden yarn[42598]: [0]     at fetch (/opt/linkwarden/node_modules/next/dist/compiled/node-fetch/index.js:1:64996)
Dec 28 16:32:13 linkwarden yarn[42598]: [0]     at fetchTitleAndHeaders (/opt/linkwarden/.next/server/pages/api/v1/links.js:618:62)
Dec 28 16:32:13 linkwarden yarn[42598]: [0]     at postLink (/opt/linkwarden/.next/server/pages/api/v1/links.js:430:123)
Dec 28 16:32:13 linkwarden yarn[42598]: [0]     at async links (/opt/linkwarden/.next/server/pages/api/v1/links.js:705:25)
```

**To Reproduce**
1. Upload a PDF file (doesn't matter whether it's a desktop or mobile).
2. Observe error.

**Expected behavior**
I'm not entirely certain what's supposed to happen when uploading a file, as I've never seen this working. I assume it's supposed to render it into a preview image, and make the PDF accessible for download when clicking on it? Instead all it does it open a new tab with `about:blank` in the address bar.

Version 2.8.4.

**Comment by NextBlaubeere** [comment]
I am experiencing the same issue.
