### ISSUE TITLE
Error: P1000: Authentication failed

### ISSUE THREAD

**Issue by rockhazard** [linkwarden/linkwarden#946]
**The following repeats when running `docker compose up`**
```
linkwarden-postgres-1    | 2024-12-30 21:34:53.119 UTC [33] FATAL:  password authentication failed for user "postgres"
linkwarden-postgres-1    | 2024-12-30 21:34:53.119 UTC [33] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  | Error: P1000: Authentication failed against database server at `postgres`, the provided database credentials for `postgres` are not valid.
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  | Please make sure to provide valid database credentials for the database server at `postgres`.
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  | error Command failed with exit code 1.
linkwarden-linkwarden-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
linkwarden-linkwarden-1 exited with code 0
linkwarden-linkwarden-1  | yarn run v1.22.19
linkwarden-linkwarden-1  | $ /data/node_modules/.bin/prisma migrate deploy
linkwarden-linkwarden-1  | Prisma schema loaded from prisma/schema.prisma
linkwarden-linkwarden-1  | Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
linkwarden-postgres-1    | 2024-12-30 21:34:54.591 UTC [34] FATAL:  password authentication failed for user "postgres"
linkwarden-postgres-1    | 2024-12-30 21:34:54.591 UTC [34] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  | Error: P1000: Authentication failed against database server at `postgres`, the provided database credentials for `postgres` are not valid.
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  | Please make sure to provide valid database credentials for the database server at `postgres`.
linkwarden-linkwarden-1  |
linkwarden-linkwarden-1  | error Command failed with exit code 1.
linkwarden-linkwarden-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
linkwarden-linkwarden-1 exited with code 1
```

**To Reproduce**
1. clone repo and cd to repo directory
2. copy and edit .env file for variables NEXTAUTH_SECRET and POSTGRES_PASSWORD
3. run `docker compose up`

**Expected behavior**
LinkWarden should be available on `localhost:3000`

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2
 - Browser: Firefox
 - Docker: 27.2

**Additional context**
- I have ensured that the db password does not contain special characters
- I have turned off my firewall in case it was causing port isues
- I have cleared docker cache

**Comment by aRustyDev** [comment]
Having the same issue
Followed the default instructions

these are the env values I've set
```
NEXTAUTH_URL=http://localhost:3001/api/v1/auth
NEXTAUTH_SECRET=VERY_SENSITIVE_SECRET
DATABASE_URL=postgresql://postgres:CUSTOM_POSTGRES_PASSWORD@postgres:5432/postgres
POSTGRES_PASSWORD=CUSTOM_POSTGRES_PASSWORD
```

I have tried docker and orbstack, no difference. 

Here is the `docker version` output 
```
docker version
Client:
 Version:           27.3.1
 API version:       1.45 (downgraded from 1.47)
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:38:18 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.31.0 (153195)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:22 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```
  
Note:  I am running on a MacOS w/ Intel CPU

**Comment by aRustyDev** [comment]
I am not sure why, but after I deleted the cloned repo and removed all traces of the compose deployment from docker, then re-cloned and deployed it with the following .env it worked. 

```
NEXTAUTH_URL=http://localhost:3001/api/v1/auth
NEXTAUTH_SECRET=VERYSENSITIVESECRET
POSTGRES_PASSWORD=CUSTOMPOSTGRESPASSWORD
```

This still feels like a bug, but I think it has something to do with using the "default" passwords and then trying to change them w/o a complete reset. 

I think at a minimum there should be a note added to the docs with password requirements, as well using some "default" password in the docs that DOESN'T need to be changed. Just add a note and we can change it. But for quick setup its much nicer to be able to just copy pasta the example.

**Comment by danielnbalasoiu** [comment]
Hi,

Stupid question: Why are you using port 3001? 
I see in the [.env.sample](https://github.com/linkwarden/linkwarden/blob/main/.env.sample#L1) file that it's `3000`.

**Comment by aRustyDev** [comment]
> Hi,
> 
> Stupid question: Why are you using port 3001? I see in the [.env.sample](https://github.com/linkwarden/linkwarden/blob/main/.env.sample#L1) file that it's `3000`.

@danielnbalasoiu Sorry for the late reply, it was just b/c I had something else on that port I think?

**Comment by grillop** [comment]
for the record, i keep getting the same error ... totally unable to fix it ... tried various things.  Functionality appears to be whole and working, but I don't know what i don't know.  Prefer to not see errors in logs

This was installed using portainer ....


Please make sure to provide valid database credentials for the database server at `postgres`.

[0]     at Mn.handleRequestError (/data/node_modules/@prisma/client/runtime/library.js:121:7753)

[0]     at Mn.handleAndLogRequestError (/data/node_modules/@prisma/client/runtime/library.js:121:7061)

[0]     at Mn.request (/data/node_modules/@prisma/client/runtime/library.js:121:6745)

[0]     at async l (/data/node_modules/@prisma/client/runtime/library.js:130:9633)

[0]     at async verifyToken (/data/apps/web/.next/server/chunks/2349.js:29:21)

[0]     at async verifyUser (/data/apps/web/.next/server/chunks/2349.js:61:19)

[0]     at async dashboard (/data/apps/web/.next/server/pages/api/v2/dashboard.js:225:18) {

[0]   code: 'P1000',

[0]   clientVersion: '5.21.1',

[0]   meta: {

[0]     modelName: 'AccessToken',

[0]     database_user: 'linkwarden',

[0]     database_host: 'postgres'

[0]   }

**Comment by Simon1511** [comment]
+1 on this. Cant even start linkwarden because apparently the postgres password is wrong.

**Comment by Simon1511** [comment]
Nevermind, seems like I fixed it. Not sure whats wrong with the default ENV provided by Linkwarden, but doing the following fixed it for me:

1. Uncomment POSTGRES_PASSWORD in the .env
2. In the docker-compose.yml, add the following to the postgres container:
```
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=linkwarden
```
3. Modify the DB URL in the docker-compose.yml for the linkwarden container:
```
    environment:
      - DATABASE_URL=postgresql://dbuser:12345@postgres:5432/linkwarden
```
4. Make sure to fully clear the "pgdata" folder (warning: this will fully clear everything saved in linkwarden) before attempting to start the container.
5. Linkwarden starts successfully

**Comment by barremian** [comment]
Exactly a year later I am still getting this issue. I finally made it to work with the following `docker-compose.yml` and `.env` file. 

- I had to remove the special characters from the Postgres password. Perhaps it does work with the special chars, but I couldn't make it to, so I removed them.
- Replace the placeholders enclosed in `<>` with actual values. The value for `<postgres-password>` must be the same in both it's usages.
- When hosting externally, IMO it's better to disable sign-ups by setting `NEXT_PUBLIC_DISABLE_REGISTRATION=true` after creating your user to avoid misuse.

**docker-compose.yml**
```yml
services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:v2.13.5
    container_name: linkwarden
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
      - meilisearch

  postgres:
    image: postgres:16-alpine
    container_name: linkwarden-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: unless-stopped
    container_name: linkwarden-meilisearch
    env_file:
      - .env
    ports:
      - 7700:7700
    volumes:
      - ./meili_data:/meili_data
```

**.env**
```dotenv
DATABASE_URL=postgresql://linkwarden-user:<postgres-password>@linkwarden-postgres:5432/linkwarden-db
NEXTAUTH_URL=http://localhost:3000/api/v1/auth
NEXTAUTH_SECRET=<nextauth-secret>
NEXT_PUBLIC_DISABLE_REGISTRATION=false

POSTGRES_USER=linkwarden-user
POSTGRES_PASSWORD=<postgres-password>
POSTGRES_DB=linkwarden-db

MEILI_HOST=http://linkwarden-meilisearch:7700
MEILI_MASTER_KEY=<meili-master-key>
```

**Comment by adamzvolanek** [comment]
Running into the same issue myself, modified a bit of the configuration above and got it working. Albeit with other errors related to changing the port from 3000.
